name: apple-app-ui-tests-workflow

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      scheme:
        required: true
        type: string
      tests:
        required: true
        type: string
    secrets:
      CRICUT_GPR_TOKEN:
        required: true

jobs:
  build:
    name: apple-app-ui-tests-workflow
    runs-on: macos-11.0
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: List Branches for this PR
      run: |
        echo github.base_ref: ${{ github.base_ref }}
        echo github.head_ref: ${{ github.head_ref }}
        echo github.ref: ${{ github.ref }}
    - name: Swift Version
      uses: fwal/setup-swift@v1
      with:
        swift-version: "5.5"
    - name: Setup Git Credentials
      run: |
        defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
        git config --global credential.helper osxkeychain
        git credential-osxkeychain store <<EOF
        protocol=https
        host=github.com
        username=cricut-builduser
        password=${{ secrets.CRICUT_GPR_TOKEN }}
        EOF
    - name: Configure SwiftPM
      run: |
        git config --global url."https://${{ secrets.CRICUT_GPR_TOKEN }}@github.com/cricut".insteadOf "https://github.com/cricut"
        for FILE in $(grep -Ril "https://github.com/cricut" . --exclude-dir=.build --exclude-dir=.swiftlint --exclude-dir=.git --exclude-dir=Carthage --exclude-dir=.ci_scripts); do
            echo "Configure PAT for: ${FILE}"
            sed -i '' "s/https:\/\/github.com\/cricut/https:\/\/${{ secrets.CRICUT_GPR_TOKEN }}@github.com\/cricut/g" ${FILE}
        done
    - name: Resolve Swift Packages
      run: |
        xcodebuild \
        -project '${{ inputs.project }}' \
        -scheme '${{ inputs.scheme }}' \
        -resolvePackageDependencies || exit 1
    - name: Run UI Tests
      run: |
        sudo xcode-select -switch /Applications/Xcode_13.2.1.app/Contents/Developer
        while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done & \
        xcodebuild test ONLY_ACTIVE_ARCH="YES" \
        -quiet \
        -configuration Debug \
        -project '${{ inputs.project }}' \
        -scheme '${{ inputs.scheme }}' \
        -only-testing:'${{ inputs.tests }}' \
        -destination 'platform=iOS Simulator,OS=latest,name=iPhone 8' || exit 1
